image: peixeaquatico/magic_phylogenetic:latest

stages:
- test

before_script:
- echo "Verifying dependencies"
- python3 -m pip install pytest
- python3 -m pip install pytest-cov

test:
  stage: test
  script:
    - echo "Running tests with coverage measurement"
    - python3 -m pytest --cov=./ TestSuit/test_getSpeciesRankName.py 
    - python3 -m pytest --cov=./ TestSuit/test_getSpeciesNamesList.py
    - python3 -m pytest --cov=./ TestSuit/test_getSpeciesGeneList.py 
    - python3 -m pytest --cov=./ TestSuit/test_getSatisfiedlist.py
    - python3 -m pytest --cov=./ TestSuit/test_getConcatAlignNamedFasta.py
    - echo "Coverage report"
    - coverage report
    - coverage xml
  coverage: '/TOTAL.*\s+(\d+\%)/'
