image: snakemake/snakemake

stages:
  - test

test:
  stage: test
  script:
    - pip3 install pytest
    - python3 -m pytest  /TestSuit/test_fasta_script.py
    - python3 -m pytest  /TestSuit/test_model_tree.py
    - python3 -m pytest  /TestSuit/test_getFiltheredGenesLists.py
    - python3 -m pytest  /TestSuit/test_getSatisfiedlist.py
    - python3 -m pytest  /TestSuit/test_getSpeciesNamesList.py
    - python3 -m pytest  /TestSuit/test_getSpeciesRankName.py
    