image: snakemake/snakemake

stages:
  - lint
  - test

lint:
  stage: lint
  script:
    - pip3 install pylint flake8
    - pylint /TestSuit
    - flake8 /TestSuit

before_script:
  - pip3 install pytest

test:
  stage: test
  script:
    - python3 -m pytest  /TestSuit/test_fasta_script.py
    - python3 -m pytest  /TestSuit/test_model_tree.py
    - python3 -m pytest  /TestSuit/test_getSatisfiedlist.py
    - python3 -m pytest  /TestSuit/test_getSpeciesNamesList.py
    - python3 -m pytest  /TestSuit/test_getSpeciesRankName.py
  artifacts:
    paths:
      - /TestSuit/test-reports