image: peixeaquatico/magic_phylogenetic:latest

stages:
- test

before_script:
- echo "Verifying dependencies"
- python3 -m pip install pytest
- python3 -m pip install pytest-cov

test:
  stage: test
  script:
    - echo "Running tests with coverage measurement"
    - python3 -m pytest TestSuit/test_getSpeciesRankName.py
    - coverage run -m pytest TestSuit/test_getSpeciesRankName.py
    - coverage report
    - python3 -m pytest TestSuit/test_getSpeciesNamesList.py
    - coverage run -m pytest TestSuit/test_getSpeciesNamesList.py
    - coverage report
    - python3 -m pytest TestSuit/test_getSpeciesGeneList.py
    - coverage run -m pytest TestSuit/test_getSpeciesGeneList.py
    - coverage report 
    - python3 -m pytest TestSuit/test_getSatisfiedlist.py
    - coverage run -m pytest TestSuit/test_getSatisfiedlist.py
    - coverage report 
    - python3 -m pytest TestSuit/test_getSatisfiedlist.py
    - coverage run -m pytest TestSuit/test_getSatisfiedlist.py
    - coverage report  
    - python3 -m pytest TestSuit/test_model_tree.py
    - coverage run -m pytest TestSuit/test_model_tree.py
    - coverage report  
    - python3 -m pytest TestSuit/test_getToyTree.py
    - coverage run -m pytest TestSuit/test_getToyTree.py
    - coverage report 
    - echo "Coverage report"
    - coverage report
    - coverage xml
  coverage: '/TOTAL.*\s+(\d+\%)/'
