 # Get docker image
image: peixeaquatico/magic_phylogenetic:latest


stages:
- test

before_script:
- echo "Verifying dependencies"
- python3 -m pip install pytest

test:
  stage: test
  script:
    - echo "Running tests"
    - python3 -m pytest TestSuit/test_getSpeciesRankName.py
    - python3 -m pytest TestSuit/test_getSpeciesNamesList.py 
    - python3 -m pytest TestSuit/test_getSatisfiedlist.py  
    - python3 -m pytest TestSuit/test_getConcatAlignNamedFasta.py 
    - python3 -m pytest TestSuit/test_model_tree.py 